In [2]:
pip install pandas

                                              0.0/10.6 MB ? eta -:--:--
                                              0.1/10.6 MB 3.3 MB/s eta 0:00:04
     -                                        0.3/10.6 MB 3.4 MB/s eta 0:00:04
     --                                       0.5/10.6 MB 4.3 MB/s eta 0:00:03
     --                                       0.8/10.6 MB 4.4 MB/s eta 0:00:03
     ---                                      0.9/10.6 MB 4.1 MB/s eta 0:00:03
     ---                                      1.0/10.6 MB 3.8 MB/s eta 0:00:03
     ----                                     1.1/10.6 MB 3.4 MB/s eta 0:00:03
     ----                                     1.2/10.6 MB 3.2 MB/s eta 0:00:03
     ----                                     1.3/10.6 MB 3.1 MB/s eta 0:00:03
     -----                                    1.4/10.6 MB 3.0 MB/s eta 0:00:04
     -----                                    1.5/10.6 MB 3.0 MB/s eta 0:00:04
     -----                                    1.6/10.6 MB 2

In [1]:
pip install pillow

                                              0.0/2.5 MB ? eta -:--:--
     -                                        0.1/2.5 MB 2.0 MB/s eta 0:00:02
     ----                                     0.3/2.5 MB 3.2 MB/s eta 0:00:01
     ---------                                0.6/2.5 MB 4.3 MB/s eta 0:00:01
     -------------                            0.9/2.5 MB 4.5 MB/s eta 0:00:01
     ---------------                          1.0/2.5 MB 4.0 MB/s eta 0:00:01
     ----------------                         1.0/2.5 MB 3.7 MB/s eta 0:00:01
     -----------------                        1.1/2.5 MB 3.6 MB/s eta 0:00:01
     -------------------                      1.2/2.5 MB 3.1 MB/s eta 0:00:01
     ---------------------                    1.3/2.5 MB 3.0 MB/s eta 0:00:01
     ----------------------                   1.4/2.5 MB 2.9 MB/s eta 0:00:01
     -----------------------                  1.5/2.5 MB 2.8 MB/s eta 0:00:01
     -------------------------                1.6/2.5 MB 2.7 MB/s eta 0

In [3]:
import numpy as np


In [4]:
np.add(5+2,5+2)

14

In [5]:
arr = np.arange(20)

In [6]:
arr2d = arr.reshape([5,4])

In [7]:
arr2d.ndim
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
arr2d[3:4]

array([[12, 13, 14, 15]])

In [19]:
arr3d = np.arange(30)
arr3d = arr3d.reshape(3,2,5)

In [20]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [21]:
# arr3d[1][1,3]
arr3d[0:1,1,2]

array([7])

In [22]:
arr2d.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
arr3d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])