In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install pillow

                                              0.0/2.5 MB ? eta -:--:--
     -                                        0.1/2.5 MB 2.0 MB/s eta 0:00:02
     ---                                      0.2/2.5 MB 2.4 MB/s eta 0:00:01
     ----                                     0.3/2.5 MB 2.0 MB/s eta 0:00:02
     ----                                     0.3/2.5 MB 2.0 MB/s eta 0:00:02
     ------                                   0.4/2.5 MB 1.7 MB/s eta 0:00:02
     -------                                  0.5/2.5 MB 1.7 MB/s eta 0:00:02
     ---------                                0.6/2.5 MB 1.8 MB/s eta 0:00:02
     ----------                               0.6/2.5 MB 1.7 MB/s eta 0:00:02
     ----------                               0.6/2.5 MB 1.7 MB/s eta 0:00:02
     ------------                             0.8/2.5 MB 1.6 MB/s eta 0:00:02
     ---------------                          0.9/2.5 MB 1.7 MB/s eta 0:00:01
     ---------------                          1.0/2.5 MB 1.6 MB/s eta 0

In [3]:
import numpy as np


In [5]:
np.add(5+2,5+2)

14

In [20]:
arr = np.arange(20)

In [45]:
arr2d = arr.reshape([5,4])

In [47]:
arr2d.ndim
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [52]:
arr2d[3:4]

array([[12, 13, 14, 15]])

In [86]:
arr3d = np.arange(20)
arr3d = arr3d.reshape(2,2,5)

In [88]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [127]:
# arr3d[1][1,3]
arr3d[0:1,1,2]

array([7])